FROM node:24.14.0-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund --loglevel error

EXPOSE 4200

CMD ["npx", "docusaurus", "start", "--host", "0.0.0.0", "--port", "4200", "--poll", "1000"]
